"use client"
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import '@style/style.scss'
import type { Metadata } from 'next'
import { Heebo } from '@next/font/google'
import { Inter } from '@next/font/google'
import NavBar from '@components/NavBar'
import { Container } from 'react-bootstrap'

const heebo = Heebo({ subsets: ['latin'] })
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${heebo.className} `}>
        <Container className='flex flex-col relative h-[100vh] border-2 border-red-500 p-0'>
          <NavBar />
          {children}
        </Container>
      </body>
    </html>
  )
}
